defaults:
  # - model_checkpoint.yaml
  - restore_checkpoint.yaml
  # - early_stopping.yaml
  - model_summary.yaml
  # - rich_progress_bar.yaml
  - lr_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  save_last: True
  auto_insert_metric_name: False
  every_n_epochs: 1
# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

model_summary:
  max_depth: 2
