

vis_encoder: null

lm_model:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: ??? # path of language model
  trust_remote_code: True

fromage:
  freeze_lm: True
  freeze_vm: True
  num_vis_tokens: 1
  # img_embed_drop_prob: float = 0.0
  # task: captioning
  shared_emb_dim: 512
  vis_hidden_size: 768
  aux_hidden_size: 768
  extra_param_dir: '' # ckpt path of extra params 
